using ProductPlanningApplication.Dtos;

namespace ProductPlanningApplication.DomainServices.Operations.Responses;

public record struct CalculateDemandSuppliedResponse(CalculateDemandSuppliedDto Demand);
