using ProductPlanningApplication.Dtos;

namespace ProductPlanningApplication.DomainServices.Operations.Responses;

public record struct CalculateAverageDailySalesResponse(CalculateAverageDailySalesDto AverageDailySales);
